figure(3);
subplot(3,2,1);
plot(timestamp, acc_s(1,:),'k-');
grid on;
xlabel('Time (s)');
subplot(3,2,3);
plot(timestamp, acc_s(2,:),'k-');
grid on;
xlabel('Time (s)');
subplot(3,2,5);
plot(timestamp, acc_s(3,:),'k-');
grid on;
xlabel('Time (s)');
subplot(3,2,2);
plot(timestamp, gyro_s(1,:),'k-');
grid on;
xlabel('Time (s)');
subplot(3,2,4);
plot(timestamp, gyro_s(2,:),'k-');
grid on;
xlabel('Time (s)');
subplot(3,2,6);
plot(timestamp, gyro_s(3,:),'k-');
grid on;
xlabel('Time (s)');